repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff-check
        description: "Run 'ruff' for extremely fast Python linting"
        language: system
        entry: ruff check --force-exclude
        types_or: [python, pyi]
      
      - id: ruff-format
        name: ruff-format
        description: "Run 'ruff format' for extremely fast Python formatting"
        language: system
        entry: ruff format --force-exclude
        types_or: [python, pyi]
